### PR TITLE
Update actix-web, tokio and sqlx

### PR DESCRIPTION
**Pull request by realaravinth**
- Changes from `actix-web`, `tokio` and `sqlx`
- update source code handler to point to this repository
- moved `render_404` from `error_handlers.rs` to `errors.rs`

### CODE REVIEW

**Review by AaronErhardt — COMMENTED** [review]
Looks good, haven't found any issues. I don't see a reason why this shouldn't be merged as probably nobody uses Triox in production so using the actix beta should be fine.

I wonder though whether actix-governor needs to be updated to work with the latest actix beta version.

**Comment by realaravinth** [comment]
`actix-governor` is currently disabled, I have left a `TODO` in `src/api/v1/mod.rs` for including it.
I don't know how it works. If I understand it correctly, a new middleware instance is created for each service and each service gets its own counter. I hope I am wrong because otherwise, it would be ineffective.

Please send a PR for enabling `actix-gernor`

**Comment by realaravinth** [comment]
and `anctix-web-4-beta.*` is reasonably stable. `v3` uses `tokio` v2 which is painfully old.

**Comment by AaronErhardt** [comment]
I'll try porting actix-governor to the latest acitx-web beta. Actually there's only one counter (that's stored in the config) despite the API indicating the opposite.

**Pull request merged**
